package io.github.kolod

import com.formdev.flatlaf.FlatLightLaf
import com.jcabi.manifests.Manifests
import org.slf4j.LoggerFactory
import java.awt.*
import java.awt.event.ItemEvent.*
import java.io.File
import java.util.*
import java.util.prefs.Preferences
import javax.imageio.ImageIO
import javax.swing.*
import javax.swing.JFileChooser.*


class GroundTruthEditor : JFrame() {
	private val logger = LoggerFactory.getLogger(GroundTruthEditor::class.java)
	private val bundle = ResourceBundle.getBundle("i18n/GroundTruthEditor")
	private val prefs = Preferences.userNodeForPackage(GroundTruthEditor::class.java)
	private var directory :File? = null
	private var id = 1

	private val imageView         = JLabel()
	private val imageViewScroll   = JScrollPane(imageView)
	private val textView          = JTextArea()
	private val textViewScroll    = JScrollPane(textView)
	private val uncheckAllButton  = JButton()
	private val browseButton      = JButton()
	private val nextButton        = JButton()
	private val previousButton    = JButton()
	private val checkButton       = JToggleButton()


	private fun loadIcons(name :String, extension :String = "png") :List<Image> {
		val toolkit = Toolkit.getDefaultToolkit()
		return listOf(16, 24, 32, 48, 64, 72, 96, 128, 256).map{ size ->
			"$name$size.$extension"
		}.mapNotNull{ path ->
			javaClass.classLoader.getResource(path)
		}.mapNotNull{ url ->
			try {
				toolkit.createImage(url)
			} catch (ex: Exception) {
				logger.warn(ex.message, ex)
				null
			}
		}
	}

	private fun translateUI() {
		with(bundle) {
			title                   = getString("title") + " " + Manifests.read("Build-Date")
			nextButton.text         = getString("next_button")
			previousButton.text     = getString("previous_button")
			checkButton.text        = getString("check_button")
			browseButton.text       = getString("browse_button")
			uncheckAllButton.text   = getString("uncheck_all_button")

			checkButton.addItemListener { event ->
				checkButton.text = when (event.stateChange) {
					SELECTED   -> getString("uncheck_button")
					DESELECTED -> getString("check_button")
					else -> ""
				}
			}
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	private fun initComponents() {
		preferredSize = Dimension(800, 600)
		defaultCloseOperation = EXIT_ON_CLOSE
		iconImages = loadIcons("icon/")


		translateUI()

		val splitter = JSplitPane(JSplitPane.VERTICAL_SPLIT, imageViewScroll, textViewScroll)

		val buttons = JPanel(FlowLayout(FlowLayout.TRAILING))
		buttons.add(uncheckAllButton)
		buttons.add(browseButton)
		buttons.add(previousButton)
		buttons.add(checkButton)
		buttons.add(nextButton)

		with (contentPane) {
			add(splitter, BorderLayout.CENTER)
			add(buttons, BorderLayout.SOUTH)
		}

		pack()
		setLocationRelativeTo(null)
		splitter.dividerLocation = splitter.height / 2
	}

	private fun open(newId :Int) :Boolean = try {
		val idStr = id.toString().padStart(4, '0')
		val pngFile = File(directory, "$idStr.png")
		val txtFile = File(directory, "$idStr.gt.txt")
		imageView.icon = ImageIcon(ImageIO.read(pngFile))
		textView.text = txtFile.readText()
		id = newId
		true
	} catch (ex :Exception) {
		//logger.error(ex.message, ex)
		false
	}

	/**
	 * Creates new form TestTrainer
	 */
	init {
		logger.info("Application started")
		initComponents()

		prefs.get("directory", null)?.let {
			directory = File(it)
		}

		uncheckAllButton.addActionListener {
			directory.list { _, filename ->
				filename.endsWith(".gt.txt")
			}?.mapNotNull { name ->
				File(directory, name).renameTo( File(directory, name.split(".").first() + ".txt"))
			}
		}

		browseButton.addActionListener {
			val dialog = JFileChooser()
			dialog.fileSelectionMode = DIRECTORIES_ONLY
			dialog.isMultiSelectionEnabled = false
			dialog.selectedFile = directory
			if (dialog.showOpenDialog(this) == APPROVE_OPTION) directory = dialog.selectedFile
			directory?.absolutePath?.let { path ->
				prefs.put("directory", path)
				logger.info("Directory: $path")
				for (i in id + 1 .. 9999) {
					if (open(i)) break
				}
			}
		}

		nextButton.addActionListener {
			for (i in id + 1 .. 9999) {
				if (open(i)) break
			}
		}

		previousButton.addActionListener {
			for (i in id - 1 downTo 1) {
				if (open(i)) break
			}
		}
	}

	companion object {
		/**
		 * @param args the command line arguments
		 */
		@JvmStatic
		fun main(args: Array<String>) {
			FlatLightLaf.setup()
			UIManager.put("defaultFont", UIManager.getFont("defaultFont").deriveFont(18f))
			SwingUtilities.invokeLater { GroundTruthEditor().isVisible = true }
		}
	}
}
